function  drawParametersSDT(d, chains, dPrime, c, accuracy, pantone)
%DRAWPARAMETERSSDT Draw the signal detection odel parameters
%against accuracy

CI = [2.5 97.5];
        fontSize = 16;
        xLim = [0 5];
        tickWidth = 1;

        F = figure; clf; hold on;
        setFigure(F, [0.2 0.2 0.6 0.5], '');

        subplot(121); hold on;
        set(gca, ...
          'xlim'       , xLim                , ...
          'xtick'      , xLim(1):tickWidth:xLim(end)            , ...
          'xticklabelrot', 0, ...
          'ylim'       , [0 1]                 , ...
          'ytick'      , 0:tickWidth:1             , ...
          'xgrid'       , 'off'                       , ...
          'ygrid'       , 'off'                       , ...
          'box'        , 'off'                     , ...
          'color'       , 'none' , ...
          'tickdir'    , 'out'                     , ...
          'layer'      , 'top'                     , ...
          'ticklength' , [0.02 0]                  , ...
          'layer'      , 'top'                     , ...
          'fontsize'   , fontSize                  );
        moveAxis(gca, [1 1 1 1], [0 0.02 0 0]);
        axis equal; axis square;

        ylabel('Accuracy', 'fontsize', fontSize+2);
        xlabel('Detection Probability', 'fontsize', fontSize+2);
        Raxes(gca, 0.01, 0.01);

        for i = 1:d.nPeople
          bounds = prctile(chains.(sprintf('d_%d', i)), CI);
          plot(bounds, [accuracy(i) accuracy(i)],  '-', ...
            'color', pantone.GlacierGray);
        end
        for i = 1:d.nPeople
          plot(dPrime(i), accuracy(i), 'o', ...
            'markersize', 6, ...
            'markerfacecolor', pantone.ClassicBlue, ...
            'markeredgecolor', 'w');
        end

          xLim = [-3 5];
      subplot(122); hold on;
        set(gca, ...
          'xlim'       , xLim                , ...
          'xtick'      , xLim(1):tickWidth:xLim(end)            , ...
          'xticklabelrot', 0, ...
          'ylim'       , [0 1]                 , ...
          'ytick'      , 0:tickWidth:1             , ...
          'xgrid'       , 'off'                       , ...
          'ygrid'       , 'off'                       , ...
          'box'        , 'off'                     , ...
          'color'       , 'none' , ...
          'tickdir'    , 'out'                     , ...
          'layer'      , 'top'                     , ...
          'ticklength' , [0.02 0]                  , ...
          'layer'      , 'top'                     , ...
          'fontsize'   , fontSize                  );
        moveAxis(gca, [1 1 1 1], [0 0.02 0 0]);
        axis equal; axis square;

        xlabel('Guessing Probability', 'fontsize', fontSize+2);
        Raxes(gca, 0.01, 0.01);

        for i = 1:d.nPeople
          bounds = prctile(chains.(sprintf('c_%d', i)), CI);
          plot(bounds, [accuracy(i) accuracy(i)],  '-', ...
            'color', pantone.GlacierGray);
        end
        for i = 1:d.nPeople
          plot(c(i), accuracy(i), 'o', ...
            'markersize', 6, ...
            'markerfacecolor', pantone.ClassicBlue, ...
            'markeredgecolor', 'w');
        end