%% Extract enter/exit point estimates and related summaries for LaTeX table
% Posterior means from oneHighThresholdNoDifferencesAsymmetricDynamics
% (joint cognitive + asymmetric environmental dynamics model).
% Samples live in models/storage/ (gitignored; too large for the repo).

clear; close all;

storageDir = '../models/storage/';
dataDir = '../data/';
engine = 'jags';
modelName = 'oneHighThresholdNoDifferencesAsymmetricDynamics_n';

dataList = {
    'citizenFrogsAll', '1'
    'citizenFrogsSecondDataSet', '2'
    };

outRows = {};
fmt = '%.3f';

for dataIdx = 1:size(dataList, 1)
    dataName = dataList{dataIdx, 1};
    expLabel = dataList{dataIdx, 2};

    load([dataDir dataName], 'd');
    fileName = sprintf('%s_%s_%s.mat', modelName, dataName, engine);
    fprintf('Loading %s ...\n', fileName);
    load([storageDir fileName], 'chains');

    nFrogs = d.nFrogs;
    arriveMean = nan(nFrogs, 1);
    leaveMean = nan(nFrogs, 1);
    phiMean = nan(nFrogs, 1);
    rhoMean = nan(nFrogs, 1);
    truthFreq = nan(nFrogs, 1);

    for j = 1:nFrogs
        a = chains.(sprintf('gammaArrive_%d', j));
        b = chains.(sprintf('gammaLeave_%d', j));
        a = a(:); b = b(:);
        arriveMean(j) = mean(a);
        leaveMean(j) = mean(b);
        if isfield(chains, sprintf('phi_%d', j))
            p = chains.(sprintf('phi_%d', j));
            phiMean(j) = mean(p(:));
        else
            phiMean(j) = mean(a ./ (a + b));
        end
        % Lag-1 autocorrelation of a 2-state Markov chain implied by
        % the enter/exit point estimates: rho_1 = 1 - enter - exit
        rhoMean(j) = 1 - arriveMean(j) - leaveMean(j);
        truthFreq(j) = mean(d.truth(j, :), 'omitnan');
    end

    fprintf('\n=== Experiment %s (%s) ===\n', expLabel, dataName);
    fprintf('%-8s %8s %8s %8s %8s %8s\n', 'Species', 'Enter', 'Exit', 'Occ', 'Truth', 'AC1');
    for j = 1:nFrogs
        name = char(string(d.frogs{j}));
        fprintf('%-8s %8.3f %8.3f %8.3f %8.3f %8.3f\n', ...
            name, arriveMean(j), leaveMean(j), phiMean(j), truthFreq(j), rhoMean(j));
        outRows(end+1, :) = {expLabel, name, arriveMean(j), leaveMean(j), ...
            phiMean(j), truthFreq(j), rhoMean(j)}; %#ok<SAGROW>
    end
end

%% Write LaTeX table
texPath = fullfile(pwd, 'transitionSummaries.tex');
fid = fopen(texPath, 'w');
fprintf(fid, '%% Auto-generated by extractTransitionSummaries.m\n');
fprintf(fid, '%% Point estimates = posterior means of gammaArrive / gammaLeave\n');
fprintf(fid, '%% from %s (both experiments).\n', modelName);
fprintf(fid, '%% Occupancy = phi = enter/(enter+exit).\n');
fprintf(fid, '%% Truth = empirical ground-truth calling frequency.\n');
fprintf(fid, '%% AC1 = 1-enter-exit (stationary lag-1 autocorrelation).\n');
fprintf(fid, '%% MCMC samples are in models/storage/ (gitignored).\n');
fprintf(fid, '\\begin{table}[t]\n');
fprintf(fid, '\\centering\n');
fprintf(fid, '\\caption{Posterior-mean Markov transition probabilities (enter~$\\gamma^{\\mathrm{in}}$, exit~$\\gamma^{\\mathrm{out}}$) for each species and experiment, the implied stationary occupancy probability $\\phi=\\gamma^{\\mathrm{in}}/(\\gamma^{\\mathrm{in}}+\\gamma^{\\mathrm{out}})$, the empirical ground-truth calling frequency, and the implied lag-1 autocorrelation $\\rho_1=1-\\gamma^{\\mathrm{in}}-\\gamma^{\\mathrm{out}}$.\\label{tab:transition}}\n');
fprintf(fid, '\\begin{tabular}{clccccc}\n');
fprintf(fid, '\\toprule\n');
fprintf(fid, 'Exp. & Species & Enter & Exit & Occupancy & Truth & AC$_1$ \\\\\n');
fprintf(fid, '\\midrule\n');

prevExp = '';
for i = 1:size(outRows, 1)
    expLabel = outRows{i, 1};
    name = outRows{i, 2};
    nameTex = strrep(name, '_', '\\_');
    nameTex = strrep(nameTex, '&', '\\&');
    if ~strcmp(expLabel, prevExp)
        if ~isempty(prevExp)
            fprintf(fid, '\\midrule\n');
        end
        expShow = expLabel;
        prevExp = expLabel;
    else
        expShow = '';
    end
    fprintf(fid, '%s & %s & %s & %s & %s & %s & %s \\\\\n', ...
        expShow, nameTex, ...
        sprintf(fmt, outRows{i, 3}), ...
        sprintf(fmt, outRows{i, 4}), ...
        sprintf(fmt, outRows{i, 5}), ...
        sprintf(fmt, outRows{i, 6}), ...
        sprintf(fmt, outRows{i, 7}));
end

fprintf(fid, '\\bottomrule\n');
fprintf(fid, '\\end{tabular}\n');
fprintf(fid, '\\end{table}\n');
fclose(fid);

csvPath = fullfile(pwd, 'transitionSummaries.csv');
T = cell2table(outRows, 'VariableNames', ...
    {'Experiment', 'Species', 'Enter', 'Exit', 'Occupancy', 'Truth', 'AC1'});
writetable(T, csvPath);

fprintf('\nWrote %s\n', texPath);
fprintf('Wrote %s\n', csvPath);
fprintf('Total rows (species x experiment): %d\n', size(outRows, 1));
fprintf('Total enter+exit point estimates: %d\n', 2 * size(outRows, 1));
