model in "/home/mdlee/Dropbox/GitHub/citizenFrogs/models/tmp/oneHighThreshold_n/oneHighThreshold_n_jags.jags"
data in "/home/mdlee/Dropbox/GitHub/citizenFrogs/models/tmp/oneHighThreshold_n/oneHighThreshold_n.data"
compile, nchains(1)
parameters in "/home/mdlee/Dropbox/GitHub/citizenFrogs/models/tmp/oneHighThreshold_n/oneHighThreshold_n_2.init"
parameters in "/home/mdlee/Dropbox/GitHub/citizenFrogs/models/tmp/oneHighThreshold_n/oneHighThreshold_n_2.seed"
initialize
update 0
monitor set alpha, thin(1)
monitor set beta, thin(1)
monitor set tau, thin(1)
monitor set phi, thin(1)
update 10
coda *, stem('samples_2_')
