% runModels

behaviorAsymmetricDynamics_2

% oneHighThresholdNoDifferences
% oneHighThresholdNoDifferencesAsymmetricDynamics
% oneHighThresholdNoDifferencesAsymmetricDynamicsCovariance
% 
% twoHighThresholdNoDifferences
% twoHighThresholdNoDifferencesAsymmetricDynamics
% 
% signalDetectionNoDifferences
% signalDetectionNoDifferencesAsymmetricDynamics