% runModels

oneHighThresholdNoDifferences
oneHighThresholdNoDifferencesAsymmetricDynamics
oneHighThresholdNoDifferencesAsymmetricDynamicsCovariance

twoHighThresholdNoDifferences
twoHighThresholdNoDifferencesAsymmetricDynamics

signalDetectionNoDifferences
signalDetectionNoDifferencesAsymmetricDynamics